name: model_train
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  run:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
        with:
          version: '0.18.1'
      - name: train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          pip install -r requirements.txt
          python train_model.py

          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md

          echo "Confusion Matrix & Feature Importance" > report.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report.md
          echo '![](./FeatureImportance.png "FeatureImportance")' >> report.md

          
          cml comment create report.md
