name: model_train
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  run:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
        with:
          version: '0.18.1'
      - name: train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          pip install -r requirements.txt
          python train_model.py
          python test.py

          echo "# Sanity check" > report2.md
          cat test.txt >> report2.md
          
          echo "# RF and LR Model Score" > report.md
          cat scores.txt >> report.md

          echo "# Confusion Matrix & Feature Importance" > report1.md
          echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '![](./FeatureImportance.png "FeatureImportance")' >> report1.md
          
          cat report2.md report.md report1.md > combined_file.md
          cml comment create combined_file.md
